stages:
  data_ingestion:
    cmd: python src/IOT_NIDS/pipeline/stage_01_data_ingestion.py
    deps:
      - src/IOT_NIDS/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/x_test
      - artifacts/data_ingestion/y_test



   evaluation:
    cmd: python src/IOT_NIDS/pipeline/stage_02_model_evaluation.py
    deps:
      - src/IOT_NIDS/pipeline/stage_02_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/x_test
      - artifacts/data_ingestion/y_test
      - artifacts/gru_model/gru_model.h5
    metrics:
    - artifacts/model_evaluation/metrics.json:
        cache: false    